<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>1C (Query)</string>
    <key>scopeName</key>
    <string>source.sdbl</string>
    <key>firstLineMatch</key>
    <string>(?i)Выбрать|Select(\s+Разрешенные|Allowed)?(\s+Различные|Distinct)?(\s+Первые|Top)?.*</string>
    <key>uuid</key>
    <string>d94265d3-2270-4ff2-ba36-649fbb4160df</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.sdbl</string>
        <key>match</key>
        <string>(//.*$)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.double.sdbl</string>
        <key>begin</key>
        <string>\"</string>
        <key>end</key>
        <string>\"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.sdbl</string>
            <key>match</key>
            <string>\"\"</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.sdbl</string>
            <key>match</key>
            <string>(^\s*//.*$)</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.language.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.]|^)(Неопределено|Undefined|Истина|True|Ложь|False|NULL)(?=[^\wа-яё]|$)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.sdbl</string>
        <key>match</key>
        <string>(?&lt;=[^\wа-яё]|^)(\d+\.?\d*)(?=[^\wа-яё]|$)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.conditional.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.]|^)(Выбор|Case|Когда|When|Тогда|Then|Иначе|Else|Конец|End)(?=[^\wа-яё]|$)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.logical.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.]|^)(НЕ|NOT|И|AND|ИЛИ|OR|В\s+ИЕРАРХИИ|IN\s+HIERARCHY|В|In|Между|Between|Есть\sNULL|Is\s+NULL|Ссылка|Refs|Подобно|Like)(?=[^\wа-яё]|$)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.comparison.sdbl</string>
        <key>match</key>
        <string>&lt;=|&gt;=|=|&lt;|&gt;</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.assignment.sdbl</string>
        <key>match</key>
        <string>(=)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.arithmetic.sdbl</string>
        <key>match</key>
        <string>(\+|-|\*|/|%)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.sdbl</string>
        <key>match</key>
        <string>(,|;)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.]|^)(Выбрать|Select|Разрешенные|Allowed|Различные|Distinct|Первые|Top|Как|As|ПустаяТаблица|EpmtyTable|Поместить|Into|Уничтожить|Drop|Из|From|((Левое|Left|Правое|Right|Полное|Full)\s+(Внешнее|Outer\s+)?Соединение|Join)|((Внутреннее\s+|Inner\s+)?Соединение|Join)|Где|Where|(Сгруппировать\s+По)|(Group\s+By)|Имеющие|Having|Объединить(\s+Все)?|Union(\s+All)?|(Упорядочить\s+По)|(Order\s+By)|Автоупорядочивание|Autoorder|Итоги|Totals|По(\s+Общие)?|By(\s+Overall)|(Только\s+)?Иерархия|(Only\s+)Hierarchy|Периодами|Periods|Индексировать|Index|Выразить|Cast|Возр|Asc|Убыв|Desc|Для\s+Изменения|(For\sUpdate(\s+Of)?)|Спецсимвол|Escape)(?=[^\wа-яё]|$)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Функции языка запросов</string>
        <key>name</key>
        <string>support.function.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.]|^)(Значение|Value|ДатаВремя|DateTime|Тип|Type)(?=\()</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Функции работы со строками</string>
        <key>name</key>
        <string>support.function.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.]|^)(Подстрока|Substring)(?=\()</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Функции работы с датами</string>
        <key>name</key>
        <string>support.function.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.]|^)(Год|Year|Квартал|Quarter|Месяц|Month|ДеньГода|DayOfYear|День|Day|Неделя|Week|ДеньНедели|Weekday|Час|Hour|Минута|Minute|Секунда|Second|НачалоПериода|BeginOfPeriod|КонецПериода|EndOfPeriod|ДобавитьКДате|DateAdd|РазностьДат|DateDiff)(?=\()</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Агрегатные функции</string>
        <key>name</key>
        <string>support.function.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.]|^)(Сумма|Sum|Среднее|Avg|Минимум|Min|Максимум|Max|Количество|Count)(?=\()</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Прочие функции</string>
        <key>name</key>
        <string>support.function.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.]|^)(ЕстьNULL|IsNULL|Представление|Presentation|ПредставлениеСсылки|RefPresentation|ТипЗначения|ValueType)(?=\()</string>
      </dict>
      <dict>
        <key>name</key>
        <string>support.type.sdbl</string>
        <key>match</key>
        <string>(?i)(?&lt;=[^\wа-яё\.])(Число|Number|Строка|String|Дата|Date)(?=[^\wа-яё]|$)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.parameter.sdbl</string>
        <key>match</key>
        <string>(&amp;[\wа-яё]+)</string>
      </dict>
    </array>
  </dict>
</plist>